### ISSUE TITLE
no archive for python3 on pypi.python.org

### ISSUE THREAD

**Issue by sblondon** [charlesthk/python-resize-image#12]
At https://pypi.python.org/pypi/python-resize-image/1.1.10 the downloadable wheel is python2 only, so it"s not installable directly with python3. It's still doable by cloning the repository, building the archive and installing it.

You could push a universal wheel or provide a basic tar.gz archive to fix it.

Cheers

**Comment by paulgoetze** [comment]
@charlesthk Any news on making v1.1.10 directly installable with Python 3? I would really appreciate it.
BTW: v1.1.3 seems to be the latest version that is installable for Python 3 (3.5 with pip in my case).

**Comment by charlesthk** [comment]
Hi @paulgoetze , I have just uploaded a new version top PyPi built as universal wheel.

Let me know if this is ok for you.

**Comment by paulgoetze** [comment]
@charlesthk works like a charm. Thanks a lot!

**Comment by charlesthk** [comment]
You are welcome !
