### ISSUE TITLE
Error using resize.resize_thumbnail 

### ISSUE THREAD

**Issue by balloch** [charlesthk/python-resize-image#15]
Code:
```
orig_img = open('/home/balloch/Data/ADE20K_2016_07_26/train/ADE_train_00000001.jpg', 'r')
newimg = Image.open(orig_img)
newimg  = resizeimage.resize_thumbnail(newimg, [328,328])
```
Returns Error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-f53382d82a9c> in <module>()
----> 1 newimg  = resizeimage.resize_thumbnail(newimg, [328,328])

/usr/local/lib/python2.7/dist-packages/resizeimage/resizeimage.pyc in resize_thumbnail(image, size)
    164     img_format = image.format
    165     img = image.copy()
--> 166     img.thumbnail((size[0], size[1]), Image.LANCZOS)
    167     img.format = img_format
    168     return img

AttributeError: 'module' object has no attribute 'LANCZOS'
```

Thoughts?

**Comment by amirouche** [comment]
What OS are you using?

You probably are missing a PIL dependency or PIL was compiled with wrong options.

**Comment by balloch** [comment]
possible. I didn't "compile" PIL so much as I used pip to install the one in the pip package manager. I am using Ubuntu 14.04

**Comment by amirouche** [comment]
My understanding is that PIL is compiled via pillow where pillow or PIL does guess the options based on what it finds on the system.

Make sure to install Pillow with full support, refer to Pillow and/or PIL documentation.

Pillow is supposed to only be wrapper package for PIL, it doesn't provide code outside the compilation and installation mechanic.

**Comment by balloch** [comment]
Sure, cool! should this be added to an FAQ section or something? I can pull request the readme if you'd like

**Comment by charlesthk** [comment]
@balloch did you managed to fix your issue ?
