### ISSUE TITLE
Image is too small, Image size : 300, Required size : 300

### ISSUE THREAD

**Issue by jabbalaci** [charlesthk/python-resize-image#16]
Hello,

I have a program that resizes a lot of images to smaller ones with width = 300px. However, if the original width is 300px, I get an error:

```
File "./06_all_together_improved.py", line 41, in process
    img = resizeimage.resize_width(img, medium_width)
  File "/home/jabba/.virtualenvs/resize_image/lib/python3.5/site-packages/resizeimage/resizeimage.py", line 31, in wrapper
    validator(image, size)
  File "/home/jabba/.virtualenvs/resize_image/lib/python3.5/site-packages/resizeimage/resizeimage.py", line 47, in _width_is_big_enough
    raise ImageSizeError(image.size[0], width)
resizeimage.imageexceptions.ImageSizeError: 'Image is too small, Image size : 300, Required size : 300'
```

The error message is misleading: "Image is too small, Image size : 300, Required size : 300". I think the correct behaviour in this case would be to leave the original image unchanged, as it was.

Here is a sample image for testing: https://d2r55xnwy6nx47.cloudfront.net/uploads/2015/11/KS_Ft.jpg

Best,

Laszlo

**Comment by charlesthk** [comment]
@jabbalaci thanks for this suggestion.
I have just release a new version to PyPi with a fix.
