### ISSUE TITLE
antialiasing problem

### ISSUE THREAD

**Issue by ProgramYazar** [charlesthk/python-resize-image#19]
I think you can replace this code for antialiasing problem:
----------------
file: resizeimage.py
--
def resize(method, image, size):
	"""
	Helper function to access one of the resize function.
	method:     one among 'crop', 'cover', 'contain', 'width', 'height' or 'thumbnail'
	image:      a Pillow image instance
	size:       a list or tuple of two integers [width, height]
	"""
	if method not in ['crop',
					  'cover',
					  'contain',
					  'width',
					  'height',
					  'thumbnail']:
		raise ValueError(u"method argument should be one of \
            'crop', 'cover', 'contain', 'width', 'height' or 'thumbnail'")
	return getattr(sys.modules[__name__], 'resize_%s' % method)(image, size, Image.ANTIALIAS)

----------------
thanks for this library 👍

**Comment by charlesthk** [comment]
Thanks for this, I updated the code accordingly.
