### ISSUE TITLE
Stretching images

### ISSUE THREAD

**Issue by silverkorn** [charlesthk/python-resize-image#23]
Hi,

Just to be sure, is this library/helper aiming on shrinking and not really stretching images?

I'm trying to upscale with the "resize_width" function to fit a given width and I get something like 
`'Image is too small, Image size : 1038, Required size : 1920'` as error.

Thank you!

**Comment by charlesthk** [comment]
hello @silverkorn ,

thanks for opening this issue.

As for now, this library is only intended for shrinking images. Indeed, stretching images might result in poor quality images.

If you think that stretching images is a useful feature, I would be very happy to get a PR for this.

Thanks.
