### ISSUE TITLE
Loss of Alpha Channel

### ISSUE THREAD

**Issue by bugsel** [charlesthk/python-resize-image#26]
This [commit](https://github.com/charlesthk/python-resize-image/commit/dba1cb84669432bacfa1bdbf133f51c68db1723f#r32075797) loses the alpha channel of images that have it.

**Comment by sblondon** [comment]
It's merged and released in 1.1.19 so I guess this issue should be closed (?).

**Comment by charlesthk** [comment]
Yes @sblondon you are right.
