### ISSUE TITLE
 wrapper() got an unexpected keyword argument 'resample'

### ISSUE THREAD

**Issue by shaozi** [charlesthk/python-resize-image#31]
When calling `resize_cover(img, size, resample=Image.BICUBIC)`, gives the following error:

```text
 wrapper() got an unexpected keyword argument 'resample'
```

**Comment by BrokenSwing** [comment]
I fixed it two years ago in https://github.com/VingtCinq/python-resize-image/pull/28 but the owner of this repository doesn't seem to maintain it anymore

**Comment by charlesthk** [comment]
@BrokenSwing @shaozi sorry for the delay, I merged PR #28 . Thanks.
