### ISSUE TITLE
Why open image with 'rw' in docs

### ISSUE THREAD

**Issue by guettli** [charlesthk/python-resize-image#7]
In the docs (https://github.com/charlesthk/python-resize-image) you use 'rw' to open the images.

```
from PIL import Image

test_img = open('test-image.jpeg', 'rw')
img = Image.open(test_img)
img = resizeimage.resize_thumbnail(img, [200, 200])
img.save('test-image-thumbnail.jpeg', img.format)
test_img.close()
```

I see no sense in opening the file for writing.

BTW, it is very common to use fd_.... as variable name for file descriptors returned by open().

You use `test_img`. That's valid python code, but fd_img would be more easy to read.

**Comment by charlesthk** [comment]
Thanks for this issue, I updated my code accordingly.
