### ISSUE TITLE
Please add helper method to resize from file_name to file_name

### ISSUE THREAD

**Issue by guettli** [charlesthk/python-resize-image#8]
Since your library operates on image objects from Pillow, I created this helper method:

```
def resize_file(in_file, out_file, size):
    with open(in_file) as fd:
        image = resizeimage.resize_thumbnail(Image.open(fd), size)
    image.save(out_file)
    image.close()
```

I think something like this would be very useful.

**Comment by charlesthk** [comment]
What you would like to have is the ability to save the resized image into a given 'out_file' ?

I suggest we add an optional parameter 'out_file' to each function and if set the image would be saved inside it ?

**Comment by guettli** [comment]
Yes, I would like to work an two file names: input_file_name, output_file_name.

The caller of this method does not need to import Image from PIL.

I would prefer a new methods. Since the new method does not use a PIL.Image as input-parameter.

For example:

```
resize_thumbnail_file(image_file_name_in, image_file_name_out, size)
```

For me the above method would be enough.

You can add this feature: if you pass (None, N) or (N, None) as size,
then the method works like the resize_height(), resize_width() methods.

**Comment by charlesthk** [comment]
I juste updated my code with two functions :
- `resize` which take the method name and a Pillow Image instance
- `resize_from_file` which take the file method name, the file_name_in and optionally the file_name_out

Tell me if that's ok for you.

**Comment by guettli** [comment]
About [b6229fa3865e46ac321fbf625d2ce77a8492acf2]

I would prefer N methods to one methods getting a string as first parameter.

IDEs like pyCharm know the N methods, but they don't know how to to auto-completion for the string "method".
